apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus
    app.kubernetes.io/part-of: inventory-quarkus
  name: inventory-quarkus
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: inventory-quarkus
status:
  loadBalancer: {}
